In [1]:
import sys
sys.path.insert(0, './scripts/')

In [2]:
from collections import defaultdict
import gc
import IDTMex
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as st

In [3]:
gc.collect()

0

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
base_path = "./ConjuntosDatos/"
endutih_path = base_path + "ENDUTIH2020/conjuntos_de_datos/"

In [6]:
endutih_vivhogar = pd.read_csv(endutih_path+"viv_hog_agrupados.csv")
endutih_res = pd.read_csv(endutih_path+"residente_agrupados.csv")

In [7]:
endutih_completa = pd.merge(endutih_vivhogar,endutih_res.drop(["UPM_DIS","ESTRATO","ENT","DOMINIO", "EST_DIS", "TLOC"], axis=1), on = ["UPM","VIV_SEL", "HOGAR"])
endutih_completa

,P1_1,P1_2,P1_3,P1_4,P1_5_1,P1_5_2,P1_5_3,P2_1,P2_2,P2_3,FAC_VIV,P4_1_1,P4_1_2,P4_1_3,P4_1_4,P4_1_5,P4_1_6,P4_1_6_1,P4_1_6_2,P4_2_1,P4_2_2,P4_2_3,P4_3,P4_4,P4_5,P4_6_1,P4_6_2,P4_6_3,P4_6_4,P4_6_5,P4_6_6,P4_7_1,P4_7_2,P4_7_3,P4_7_4,P4_8,P5_1,P5_2_1,P5_2_2,P5_3_1,P5_3_2,P5_4,P5_5,P5_6_1,P5_6_2,P5_6_3,P5_6_4,P5_6_5,P5_7_1,P5_7_2,P5_8_2,P5_9_2,P5_10_2,P5_7_3,P5_8_3,P5_7_4,P5_8_4,P5_9_4,P5_7_5,P5_8_5,P5_7_6,P5_8_6,P5_7_7,P5_8_7,P5_7_8,P5_8_8,P5_11_1,P5_11_2,P5_11_3,FAC_HOG,DOMINIO,TLOC,ESTRATO,Grupo_x,UPM,UPM_DIS,EST_DIS,ENT,HOGAR,VIV_SEL,NUM_REN,PAREN,SEXO,EDAD,DIA,MES,P3_7,NIVEL,GRADO,P3_9_1,P3_9_2,P3_9_3,P3_10,P3_11,P3_12,FAC_HOGAR,Grupo_y
0,2,1,1,1,1,2,2,2,1,1.0,572,2,1,1,2,2,1,2.0,2.0,2,2,2,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,1.0,2,2,2,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,3.0,3.0,3.0,575,U,1,1,11,206264,570,17,2,1,1,1,1,2,54,27.0,3.0,2.0,0.0,0.0,9.0,9.0,1.0,6.0,4.0,NaN,575,11
1,2,1,1,1,1,2,2,2,1,1.0,572,2,1,1,2,2,1,2.0,2.0,2,2,2,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,1.0,2,2,2,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,3.0,3.0,3.0,575,U,1,1,11,206264,570,17,2,1,1,2,3,2,22,7.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,1.0,NaN,1.0,575,11
2,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,1,1,2,36,29.0,6.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,575,11
3,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,2,3,1,20,29.0,3.0,2.0,6.0,2.0,1.0,1.0,1.0,1.0,NaN,1.0,575,11
4,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,3,3,2,19,20.0,2.0,2.0,6.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,575,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205276,3,1,1,1,1,1,1,5,1,1.0,271,1,2,2,1,1,1,5.0,5.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,1.0,3.0,271,U,1,4,42,3201181,8162,340,32,1,3,5,3,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,271,42
205277,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,1,1,1,43,16.0,9.0,2.0,7.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,271,42
205278,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,2,2,2,46,25.0,4.0,2.0,7.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,271,42
205279,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,3,3,1,15,8.0,12.0,1.0,3.0,3.0,1.0,1.0,1.0,5.0,4.0,NaN,271,42
205280,3,1,1,1,1,1,1,1,1,1.0,271,1,1,2,1,2,1,1.0,1.0,2,1,1,0.0,1,3.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,0.0,2,0.0,0.0,0.0,0.0,5.0,1,1,2,1,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,250.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,3.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,5,1,1,2,41,24.0,1.0,2.0,10.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,271,42

In [8]:
estados = pd.read_csv(base_path+"CodigoEdos.csv")
estados

    Codigo                            Nombre        ENT
0        1                    Aguascalientes       Ags.
1        2                   Baja California       B.C.
2        3               Baja California Sur      B.C.S
3        4                          Campeche      Camp.
4        5              Coahuila de Zaragoza      Coah.
5        6                            Colima       Col.
6        7                           Chiapas      Chis.
7        8                         Chihuahua      Chih.
8        9                  Ciudad de México     C.D.Mx
9       10                           Durango       Dgo.
10      11                        Guanajuato       Gto.
11      12                          Guerrero       Gro.
12      13                           Hidalgo       Hgo.
13      14                           Jalisco       Jal.
14      15                  Estado de México  Edo. Méx.
15      16               Michoacán de Ocampo      Mich.
16      17                           Morelos       Mor.
17      18                           Nayarit       Nay.
18      19                        Nuevo León       N.L.
19      20                            Oaxaca       Oax.
20      21                            Puebla       Pue.
21      22                         Querétaro       Qro.
22      23                      Quintana Roo    Q. Roo.
23      24                   San Luis Potosí      S.L.P
24      25                           Sinaloa       Sin.
25      26                            Sonora       Son.
26      27                           Tabasco       Tab.
27      28                        Tamaulipas     Tamps.
28      29                          Tlaxcala      Tlax.
29      30  Veracruz de Ingancio de la Llave       Ver.
30      31                           Yucatán       Yuc.
31      32                         Zacatecas       Zac.

# INTERNET

## Estados

In [15]:
estados_IDT = pd.DataFrame(endutih_res.groupby("ENT").apply(lambda x: 100*sum(x[x.P3_9_2==1].FAC_HOGAR)/sum(x.FAC_HOGAR)))
estados_IDT.columns = ["Internet"]
estados_IDT["NOMBRE"] = [nombre for nombre in estados.Nombre]
estados_IDT.loc[15,"NOMBRE"] = "México"
estados_IDT.loc[30,"NOMBRE"] = "Veracruz de Ignacio de la Llave"
estados_IDT

      Internet                           NOMBRE
ENT
1    67.271800                   Aguascalientes
2    72.905787                  Baja California
3    72.062635              Baja California Sur
4    61.603330                         Campeche
5    65.189570             Coahuila de Zaragoza
6    73.999842                           Colima
7    34.535511                          Chiapas
8    68.677784                        Chihuahua
9    78.655520                 Ciudad de México
10   67.087334                          Durango
11   56.585586                       Guanajuato
12   47.653374                         Guerrero
13   59.829156                          Hidalgo
14   66.587151                          Jalisco
15   68.457374                           México
16   48.110656              Michoacán de Ocampo
17   62.569580                          Morelos
18   60.832625                          Nayarit
19   74.461769                       Nuevo León
20   45.263294                           Oaxaca
21   51.505580                           Puebla
22   58.023016                        Querétaro
23   73.535886                     Quintana Roo
24   58.597681                  San Luis Potosí
25   66.990975                          Sinaloa
26   73.905935                           Sonora
27   54.506774                          Tabasco
28   72.544605                       Tamaulipas
29   56.140577                         Tlaxcala
30   50.882707  Veracruz de Ignacio de la Llave
31   64.550959                          Yucatán
32   53.414973                        Zacatecas

In [16]:
estados_IDT.to_csv(base_path+"estado_Internet.csv")

### Agregando Dominio Estrato

In [13]:
estrato_dom_ent = pd.DataFrame(endutih_res.groupby(["DOMINIO","ESTRATO","ENT"]).apply(lambda x: 100*sum(x[x.P3_9_2==1].FAC_HOGAR)/sum(x.FAC_HOGAR)))
estrato_dom_ent.columns = ["Internet"]
estrato_dom_ent = estrato_dom_ent.reset_index()
estrato_dom_ent = pd.pivot_table(estrato_dom_ent, index=["DOMINIO", "ESTRATO"], columns=["ENT"], fill_value=0)
estrato_dom_ent.columns = estados.ENT
estrato_dom_ent

ENT                   Ags.       B.C.      B.C.S      Camp.      Coah.  \
DOMINIO ESTRATO
R       1         0.000000  37.838199  45.267231  42.097967  29.262009
        2        59.611383  56.957958  68.558826   0.000000  41.645272
U       1         0.000000  62.962963  64.195736  49.475846  26.666667
        2        61.578031  70.681656  70.311248  70.053100  62.738417
        3        71.708698  79.618381  79.458837  82.193327  70.967118
        4        88.135899  83.123072  84.390269  82.599076  84.718294

ENT                   Col.      Chis.      Chih.     C.D.Mx       Dgo.  \
DOMINIO ESTRATO
R       1        60.258666  18.787734  31.725011   0.000000  36.184701
        2        64.812115  39.497450  55.556575  73.757609  57.119163
U       1         0.000000  29.924302  63.157895  68.000000  89.101120
        2        70.579166  56.804299  67.625349  73.503883  69.424781
        3        81.448357  76.201337  74.906532  80.589542  79.354983
        4        85.132270  88.022918  85.657147  87.328488  86.987618

ENT                   Gto.        Gro.       Hgo.       Jal.  Edo. Méx.  \
DOMINIO ESTRATO
R       1        44.239635   32.008188  41.031460  34.233240  31.910233
        2        42.884346    0.000000  59.236208  53.352379  58.598035
U       1        64.100316   50.366856  91.666667  58.823529  54.811515
        2        55.861880   61.746177  67.432236  63.849548  70.871663
        3        70.462109   75.393458  78.613417  72.153502  77.806124
        4        83.741308  100.000000  85.545265  86.581006  87.117536

ENT                  Mich.       Mor.       Nay.       N.L.       Oax.  \
DOMINIO ESTRATO
R       1        19.577924  51.058810  27.143582  46.926703  36.039068
        2        45.365468  55.003654  50.667641  82.921373  56.438291
U       1        28.400398  48.372807   0.000000  29.556114  31.370943
        2        54.263104  62.726204  63.985024  70.145676  60.345462
        3        69.996670  74.806885  79.056116  77.743786  80.015308
        4        82.300514  85.134177  89.236983  87.773315  82.178486

ENT                   Pue.       Qro.    Q. Roo.      S.L.P       Sin.  \
DOMINIO ESTRATO
R       1        36.063445  39.939696  42.396911  31.771442  46.425423
        2        46.410127  59.746363  56.902849  56.866759  50.363399
U       1        32.184014  35.822864  69.100059  20.062831  75.000000
        2        56.026257  67.523114  74.646621  65.640402  68.346231
        3        75.394303  78.835176  82.977058  78.055507  77.091233
        4        84.463521  86.263525  92.365814  89.563731  82.425360

ENT                   Son.       Tab.     Tamps.      Tlax.       Ver.  \
DOMINIO ESTRATO
R       1        42.734730  41.140819  53.664522  35.692132  30.694845
        2        61.831423  47.255329  60.998010  52.768799  47.873357
U       1        52.768934  44.507499  70.570317  41.398198  33.190044
        2        71.999538  63.616143  71.980297  56.494328  60.466885
        3        81.477499  74.968735  78.908957  68.381789  78.053209
        4        89.644191  86.247887  80.860075  76.693897  85.146482

ENT                   Yuc.       Zac.
DOMINIO ESTRATO
R       1        44.765623  32.314571
        2        67.334486  43.715500
U       1        49.518069   0.000000
        2        67.325473  53.276602
        3        80.863091  74.042361
        4        86.869153  85.596742

In [14]:
estrato_dom_ent.to_csv(base_path+"estrato_dominio_estado_internet.csv")

### Agregando Educacion

In [13]:
endutih_res.columns

Index(['UPM', 'VIV_SEL', 'HOGAR', 'NUM_REN', 'PAREN', 'SEXO', 'EDAD', 'DIA',
       'MES', 'P3_7', 'NIVEL', 'GRADO', 'P3_9_1', 'P3_9_2', 'P3_9_3', 'P3_10',
       'P3_11', 'P3_12', 'FAC_HOGAR', 'UPM_DIS', 'EST_DIS', 'DOMINIO', 'TLOC',
       'ESTRATO', 'ENT'],
      dtype='object')

In [14]:
edu_ent = pd.DataFrame(endutih_res.groupby(["NIVEL","ENT"]).apply(lambda x: 100*sum(x[x.P3_9_2==1].FAC_HOGAR)/sum(x.FAC_HOGAR)))
edu_ent.columns = ["Internet"]
edu_ent = edu_ent.reset_index()
edu_ent = pd.pivot_table(edu_ent, index=["NIVEL"], columns=["ENT"], fill_value=0)
edu_ent.columns = estados.ENT
edu_ent

ENT,Ags.,B.C.,B.C.S,Camp.,Coah.,Col.,Chis.,Chih.,C.D.Mx,Dgo.,Gto.,Gro.,Hgo.,Jal.,Edo. Méx.,Mich.,Mor.,Nay.,N.L.,Oax.,Pue.,Qro.,Q. Roo.,S.L.P,Sin.,Son.,Tab.,Tamps.,Tlax.,Ver.,Yuc.,Zac.
NIVEL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0.0,10.331585,19.583409,14.949135,11.601870,7.455663,15.618633,3.127588,11.973937,16.875429,8.531746,5.898137,2.672877,5.475142,8.629611,6.610109,6.196062,6.193478,9.553449,15.156448,3.459635,2.808048,9.356400,17.749303,3.116160,11.250134,21.179518,5.714169,9.852148,3.461332,5.389910,6.360384,5.086570
1.0,58.646840,81.654290,61.254669,34.854000,65.785023,76.445763,11.621650,56.734933,76.833290,66.915958,48.510395,23.334409,47.858297,49.885541,51.115021,38.087915,60.159838,46.192690,76.290886,29.000058,39.104167,44.470720,52.628187,42.090453,65.097595,78.118137,35.451873,59.178967,43.525000,37.983293,52.552338,30.022475
2.0,51.945640,63.826783,61.869800,45.501236,51.777912,61.400144,18.595010,53.703421,60.232135,52.603773,45.801917,33.330023,45.547924,53.946001,53.744169,35.280262,50.353884,46.140734,60.172339,30.932309,35.939276,42.276930,58.742270,39.694799,50.845905,62.534988,37.291465,59.779875,42.139157,34.034137,50.705068,38.287237
3.0,77.035527,81.881275,77.186443,70.890561,72.070914,84.392473,46.051107,77.421528,80.909289,79.017291,67.152835,60.871780,67.114678,78.035713,73.714137,58.584690,66.249663,69.363143,82.409921,60.336907,61.307542,67.481429,81.360801,66.072000,76.144828,83.051329,61.687267,82.322507,60.457807,65.589698,75.990507,60.395917
4.0,50.909091,85.198029,51.523358,75.368797,60.107266,21.800948,79.802956,70.802139,75.881005,84.734763,60.515914,30.762818,83.819629,46.296692,71.974599,69.929763,84.024641,72.693727,75.298805,57.247706,56.407335,72.619534,100.000000,86.390149,66.335815,80.463205,100.000000,71.807179,58.851548,51.128871,100.000000,59.469154
5.0,81.010038,92.165400,81.221833,79.450191,81.545699,89.207623,76.132262,77.905076,78.151016,73.882245,61.910933,69.125470,81.954032,76.347013,85.538142,77.660151,71.176676,76.332938,82.418128,69.014947,61.710093,79.835316,88.973088,71.709410,76.457042,85.106552,70.446483,77.013792,64.432890,75.636310,83.826252,64.192660
6.0,89.897908,91.440618,92.180846,90.094149,87.984304,93.316687,73.494956,91.488277,91.758897,93.043896,88.230900,80.233393,88.480537,89.914114,89.622316,78.620936,84.304339,86.127325,95.396589,82.853979,81.207589,91.525424,94.154209,86.559880,89.489311,94.461072,78.981458,92.870616,79.761806,80.848394,91.377012,86.394622
7.0,95.546535,92.303560,88.943522,85.485838,87.367518,94.344102,84.008559,88.150457,88.471779,94.890870,86.097895,95.108740,89.936504,94.738746,89.717765,80.646944,79.984693,93.861181,95.412939,76.583918,84.533462,92.418123,94.970792,93.899268,94.309440,94.217515,92.492656,83.920353,83.015899,81.283532,92.892748,89.635544
8.0,96.727267,97.088360,96.849796,96.894521,94.413258,96.837450,93.197726,97.213712,96.134399,97.291284,95.593854,94.502101,95.539123,95.680022,96.987109,91.371299,95.600769,95.529986,97.930633,94.256652,94.477690,97.422387,98.829422,96.684587,94.772598,98.499023,91.800955,96.529144,92.801758,94.308549,97.590421,92.986311
9.0,100.000000,100.000000,100.000000,100.000000,87.755955,88.440860,100.000000,100.000000,100.000000,100.000000,93.300191,100.000000,89.627415,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,81.181708,93.988030,89.110861,86.733215,100.000000,100.000000,100.000000,100.000000,63.500000,100.000000,93.402199,100.000000
10.0,98.906204,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,98.606068,99.413042,100.000000,98.210415,90.057389,100.000000,96.201582,98.135584,100.000000,100.000000,95.150362,98.186133,94.628393,91.571569,100.000000,98.171269,96.808869,100.000000,100.000000,100.000000,97.908216,97.859779,95.672683,100.000000,100.000000
11.0,100.000000,100.000000,100.000000,89.961140,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,82.839524,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,95.955370,100.000000,100.000000,100.000000,95.153134,100.000000,100.000000,100.000000,100.000000,79.610469,100.000000
99.0,55.546918,51.166047,54.799016,53.226314,32.629705,81.975251,52.129309,61.452954,61.879067,50.350195,44.981175,39.897602,29.811231,62.610309,47.189910,36.825086,55.886750,51.569375,78.184991,36.410574,30.341880,59.206215,58.761528,33.767280,44.224708,68.759445,50.028566,53.121104,29.393140,46.506382,51.230395,32.416268

In [15]:
edu_ent.to_csv(base_path+"edu_estado_internet.csv")

### Agregando Grupo

In [9]:
grupo_ent = pd.DataFrame(endutih_res.groupby(["Grupo","ENT"]).apply(lambda x: 100*sum(x[x.P3_9_2==1].FAC_HOGAR)/sum(x.FAC_HOGAR)))
grupo_ent.columns = ["Internet"]
grupo_ent = grupo_ent.reset_index()
grupo_ent = pd.pivot_table(grupo_ent, index="Grupo", columns=["ENT"], fill_value=0)
grupo_ent.columns = estados.ENT
grupo_ent

ENT,Ags.,B.C.,B.C.S,Camp.,Coah.,Col.,Chis.,Chih.,C.D.Mx,Dgo.,Gto.,Gro.,Hgo.,Jal.,Edo. Méx.,Mich.,Mor.,Nay.,N.L.,Oax.,Pue.,Qro.,Q. Roo.,S.L.P,Sin.,Son.,Tab.,Tamps.,Tlax.,Ver.,Yuc.,Zac.
Grupo,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11,0.000000,39.763300,58.702609,44.405584,29.092614,60.258666,21.088581,32.638423,68.000000,43.261046,45.395469,37.636377,41.477329,36.253399,38.493884,21.769497,50.173566,27.143582,45.112651,35.208635,34.706688,39.743650,56.351411,30.587335,47.886262,45.329051,41.620804,56.847330,37.637426,31.157022,47.781054,32.314571
20,60.448662,69.195102,69.565395,70.137821,59.868564,69.606995,54.980551,65.432892,73.373846,65.774389,51.679899,61.970538,64.847676,60.875320,69.428552,51.901480,61.363587,60.156333,72.577853,59.520275,55.385199,64.365521,73.546358,64.274054,63.325348,70.193487,58.897192,71.226704,55.798563,58.156706,67.321476,49.341721
21,68.891281,80.964256,88.601168,80.337375,40.879912,75.259516,66.666667,0.000000,83.388581,100.000000,76.192647,47.405152,76.742424,89.981711,73.949973,83.218828,80.770257,95.317616,75.000000,90.990028,75.000000,78.333830,90.787833,80.000000,100.000000,82.431457,71.758154,100.000000,61.702128,69.143747,83.604310,90.731315
22,86.289561,45.681558,73.090764,68.606766,60.922587,85.174626,79.067386,100.000000,69.412537,49.773756,74.903231,48.950343,44.273080,91.278180,84.479155,54.036520,59.910626,56.616564,84.954128,57.055129,29.072489,64.796537,82.413269,65.754496,66.691569,66.062485,69.842335,75.780637,60.633914,69.554862,67.132867,49.788016
23,52.375523,39.878939,85.240464,60.187110,41.357598,67.286245,26.245132,0.000000,100.000000,50.000000,62.419206,56.853933,68.631045,83.646712,100.000000,46.807438,37.318276,34.766881,0.000000,65.070527,0.000000,83.572196,75.711864,48.769231,64.389449,50.000000,64.704051,66.633400,14.742590,73.373260,54.424040,39.471326
30,75.744519,84.915771,77.470550,100.000000,73.073276,78.203343,0.000000,61.858530,89.300407,0.000000,85.431226,0.000000,0.000000,77.534218,59.989123,89.142531,68.836471,87.996912,86.145377,90.880282,0.000000,47.405112,87.066779,77.272727,79.686854,76.183579,61.423841,82.620126,100.000000,54.228661,83.220147,90.422662
31,58.256820,84.021222,78.660050,100.000000,26.079665,80.709534,65.044113,77.826495,72.806882,79.899135,80.798334,50.643777,0.000000,24.610745,46.652730,71.396797,81.808207,54.856469,58.689655,0.000000,25.000000,88.217605,83.811231,100.000000,67.178734,75.053533,0.000000,70.335902,100.000000,78.666915,84.288355,100.000000
32,59.447005,80.915203,0.000000,73.426573,100.000000,100.000000,0.000000,62.748780,79.192929,0.000000,82.287112,0.000000,67.580854,73.278863,87.998920,80.051370,89.789407,100.000000,74.232199,100.000000,91.393990,89.053166,87.351575,62.500000,57.900736,86.510067,80.000000,79.450851,0.000000,80.108726,84.677746,50.000000
33,71.996056,79.372999,79.604143,81.336744,70.943227,81.294773,77.055089,74.968792,80.421741,79.304495,69.978602,76.098341,79.159668,72.470689,78.318327,69.892751,74.421823,79.216714,77.761562,78.778204,75.430973,78.755654,82.825159,78.088286,77.308963,81.495099,74.841348,78.958199,68.277275,78.503951,80.992597,73.891403
34,68.284024,84.982014,78.680203,88.972431,78.923218,86.492622,0.000000,75.000000,100.000000,100.000000,58.488284,0.000000,0.000000,61.363427,0.000000,54.538653,72.620266,77.327935,75.000000,100.000000,0.000000,78.291194,83.131068,33.226837,82.182378,88.010753,100.000000,58.547009,46.292776,50.000000,67.439097,75.928918
40,77.886073,90.833626,92.688290,56.741958,80.357574,95.017857,0.000000,50.000000,94.220286,100.000000,96.021297,0.000000,0.000000,82.806715,87.738925,76.790123,0.000000,88.030468,79.049431,0.000000,100.000000,90.044475,100.000000,66.666667,94.342261,100.000000,100.000000,81.173629,50.000000,0.000000,90.425075,0.000000
41,90.148368,100.000000,68.533333,100.000000,100.000000,89.683735,100.000000,100.000000,65.911597,100.000000,100.000000,0.000000,0.000000,88.310645,0.000000,83.893709,100.000000,0.000000,100.000000,0.000000,67.465548,100.000000,100.000000,100.000000,41.129944,84.667093,100.000000,79.808990,75.000000,0.000000,70.215934,0.000000
42,87.844982,82.523611,84.384835,82.899902,84.270149,84.647153,88.069141,86.019283,87.418085,86.510900,83.592336,100.000000,85.545265,87.187292,87.207769,82.589670,82.955574,88.948943,87.700318,82.178486,84.617402,85.926459,91.843310,89.522613,82.225464,89.513975,85.443250,80.442319,77.031292,86.566958,86.911518,85.190303
43,100.000000,100.000000,100.000000,100.000000,100.000000,75.000000,75.000000,0.000000,93.734929,0.000000,86.513886,0.000000,0.000000,76.825646,84.625248,0.000000,100.000000,100.000000,93.781369,0.000000,82.162708,100.000000,100.000000,93.240265,100.000000,100.000000,0.000000,100.000000,0.000000,100.000000,100.000000,100.000000
44,91.854839,100.000000,66.666667,100.000000,0.000000,88.714734,0.000000,0.000000,66.666667,0.000000,60.984658,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,0.000000,0.000000,0.000000,77.295492,0.000000,0.000000,82.090699,92.256671,100.000000,100.000000,0.000000,0.000000,92.120462,0.000000

In [11]:
grupo_ent.to_csv(base_path+"grupo_ent_internet.csv")

# IDTMEX

## Estados

In [16]:
estados_IDT = pd.DataFrame(endutih_completa.groupby("ENT").apply(IDTMex.IDTMex))
estados_IDT.columns = ["IDTMex"]
estados_IDT["NOMBRE"] = [nombre for nombre in estados.Nombre]
estados_IDT.loc[15,"NOMBRE"] = "México"
estados_IDT.loc[30,"NOMBRE"] = "Veracruz de Ignacio de la Llave"
estados_IDT

       IDTMex                           NOMBRE
ENT
1    5.570527                   Aguascalientes
2    6.506955                  Baja California
3    5.887514              Baja California Sur
4    4.820829                         Campeche
5    5.594804             Coahuila de Zaragoza
6    5.833159                           Colima
7    3.205746                          Chiapas
8    5.753718                        Chihuahua
9    7.365574                 Ciudad de México
10   4.936638                          Durango
11   4.905484                       Guanajuato
12   4.320220                         Guerrero
13   4.426959                          Hidalgo
14   5.711634                          Jalisco
15   5.831882                           México
16   4.335930              Michoacán de Ocampo
17   5.419976                          Morelos
18   5.092683                          Nayarit
19   6.594797                       Nuevo León
20   3.881230                           Oaxaca
21   4.568140                           Puebla
22   5.160469                        Querétaro
23   5.518045                     Quintana Roo
24   4.927754                  San Luis Potosí
25   5.179816                          Sinaloa
26   6.569573                           Sonora
27   4.429494                          Tabasco
28   5.658275                       Tamaulipas
29   4.607431                         Tlaxcala
30   4.272672  Veracruz de Ignacio de la Llave
31   4.885045                          Yucatán
32   4.913732                        Zacatecas

In [17]:
estados_IDT.to_csv(base_path+"estado_IDTMex.csv")

### Agregando Dominio Estrato

In [18]:
estrato_dom_ent = pd.pivot_table(endutih_completa, index=["ESTRATO","DOMINIO"], columns=["ENT"], aggfunc=IDTMex.IDTMex, fill_value=0)
estrato_dom_ent.columns = estados.ENT
estrato_dom_ent

C:\Users\jazmi\AppData\Local\Temp\ipykernel_4772\51645350.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
  estrato_dom_ent = pd.pivot_table(endutih_completa, index=["ESTRATO","DOMINIO"], columns=["ENT"], aggfunc=IDTMex.IDTMex, fill_value=0)

ENT                  Ags.      B.C.     B.C.S     Camp.     Coah.      Col.  \
ESTRATO DOMINIO
1       R        0.000000  3.411529  3.066407  3.058415  2.214322  3.963927
        U        0.000000  5.046326  5.006640  3.352829  2.779101  0.000000
2       R        4.725385  4.729237  5.170408  0.000000  3.118111  4.493958
        U        4.771245  6.056945  5.574387  5.463141  5.079257  5.282509
3       U        6.188671  7.154759  6.607230  6.754951  6.208204  6.706178
4       U        7.420776  7.868997  7.723561  6.991155  7.854124  7.514476

ENT                 Chis.     Chih.    C.D.Mx      Dgo.      Gto.      Gro.  \
ESTRATO DOMINIO
1       R        1.927872  2.596100  0.000000  2.493391  3.622589  3.012724
        U        2.854510  6.896296  4.913072  7.303790  4.612415  4.227316
2       R        3.168165  4.235957  6.175713  3.861251  3.569197  0.000000
        U        4.688881  5.418688  6.693256  4.847668  4.709765  5.366548
3       U        6.635687  6.300245  7.515612  6.277487  6.388651  7.453868
4       U        6.931199  7.666491  8.529377  7.067138  7.771678  8.416667

ENT                  Hgo.      Jal.  Edo. Méx.     Mich.      Mor.      Nay.  \
ESTRATO DOMINIO
1       R        2.940582  2.942555   2.878523  2.294252  4.014961  2.402178
        U        4.626263  2.822222   3.989717  2.558556  4.120816  0.000000
2       R        4.164307  4.515803   4.872147  4.036304  5.053108  3.719328
        U        4.913299  5.185182   5.767980  4.672335  5.374207  5.252341
3       U        6.404330  6.187169   6.849250  6.036802  6.442413  6.992139
4       U        7.234888  7.992761   7.847352  7.329075  7.498172  8.081349

ENT                  N.L.      Oax.      Pue.      Qro.   Q. Roo.     S.L.P  \
ESTRATO DOMINIO
1       R        3.902891  3.048186  3.074114  3.373671  2.829675  2.527151
        U        3.097799  2.908738  2.782734  3.930312  4.541718  2.422759
2       R        6.996182  4.353726  3.995110  4.843397  3.403262  4.064482
        U        5.804778  5.030919  4.792183  5.931734  5.505948  5.316379
3       U        6.912412  7.006197  6.648670  6.966516  6.689284  6.703055
4       U        8.237719  8.367244  7.724657  7.845175  7.425358  7.664806

ENT                  Sin.      Son.      Tab.    Tamps.     Tlax.      Ver.  \
ESTRATO DOMINIO
1       R        3.159647  3.953149  3.208921  3.789917  2.416861  2.657592
        U        4.487582  5.013222  3.171525  4.799163  3.247217  2.645744
2       R        3.657433  4.848760  3.712441  4.717778  4.131188  3.749432
        U        5.028904  6.145511  5.089826  5.417895  4.588080  4.924296
3       U        6.250312  7.222358  6.557739  6.366178  6.480516  6.593835
4       U        7.134141  8.674763  8.015262  7.176569  6.653450  7.468844

ENT                  Yuc.      Zac.
ESTRATO DOMINIO
1       R        3.122539  3.084682
        U        3.374351  0.000000
2       R        3.989205  3.798105
        U        4.893001  4.981891
3       U        6.638981  6.646915
4       U        7.279080  7.840640

In [19]:
estrato_dom_ent.to_csv("./ConjuntosDatos/estrato_dominio_estado_IDTMex.csv")

### Agregando Educacion

In [20]:
edu_ent = pd.pivot_table(endutih_completa, index=["NIVEL"], columns=["ENT"], aggfunc=IDTMex.IDTMex, fill_value=0)
edu_ent.columns = estados.ENT
edu_ent

C:\Users\jazmi\AppData\Local\Temp\ipykernel_4772\2516472346.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
  edu_ent = pd.pivot_table(endutih_completa, index=["NIVEL"], columns=["ENT"], aggfunc=IDTMex.IDTMex, fill_value=0)
C:\Users\jazmi\Documents\Uni\Tesis\Experimentos\DivisionDigitalMX\./scripts\IDTMex.py:79: RuntimeWarning: invalid value encountered in longlong_scalars
  alfabetas_proxy = residentes[(residentes.EDAD>=18)&(residentes.NIVEL>=2)].FAC_HOGAR.sum()/residentes[residentes.EDAD>=18].FAC_HOGAR.sum()
C:\Users\jazmi\Documents\Uni\Tesis\Experimentos\DivisionDigitalMX\./scripts\IDTMex.py:82: RuntimeWarning: invalid value encountered in longlong_scalars
  bachillerato = residentes[(residentes.EDAD>=18)&(residentes.NIVEL>=6)].FAC_HOGAR.sum()/residentes[residentes.EDAD>=18].FAC_HOGAR.sum()
C:\Users\jazmi\Documents\Uni\Tesis\Experimentos\DivisionDigitalMX\./scripts\IDTMex.py:85: RuntimeWarning: invalid value encountered in longlong_scalars
  universidad = residentes[(residentes.EDAD>=23)&(residentes.NIVEL>=8)].FAC_HOGAR.sum()/residentes[residentes.EDAD>=23].FAC_HOGAR.sum()

ENT,Ags.,B.C.,B.C.S,Camp.,Coah.,Col.,Chis.,Chih.,C.D.Mx,Dgo.,Gto.,Gro.,Hgo.,Jal.,Edo. Méx.,Mich.,Mor.,Nay.,N.L.,Oax.,Pue.,Qro.,Q. Roo.,S.L.P,Sin.,Son.,Tab.,Tamps.,Tlax.,Ver.,Yuc.,Zac.
NIVEL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0.0,2.359107,3.060310,2.318015,1.831283,2.059401,2.362057,1.041315,2.240384,3.273032,1.728138,1.891167,1.697744,1.550950,2.464762,2.071529,1.768460,2.415985,1.951932,2.954884,1.358215,1.518219,1.744263,2.240095,1.521166,2.084867,2.820423,1.599926,2.398662,1.543840,1.669642,1.841050,1.822226
1.0,3.768268,5.575672,4.443130,2.967539,4.533743,4.558078,1.652119,4.996707,6.204009,4.046730,3.506731,2.527729,3.200385,0.000000,0.000000,3.081875,4.153898,3.443029,5.375970,2.586244,3.233206,3.954183,3.346993,3.148755,4.097509,5.788299,2.754790,4.650393,3.087900,3.219967,3.608233,3.583574
2.0,4.467121,5.650719,4.949301,3.784618,4.502927,4.783676,2.509247,4.612109,5.988086,3.957398,4.142170,3.578763,3.677097,4.767233,4.775790,3.566438,4.469164,4.144598,5.560759,3.194810,3.602564,4.011192,4.423211,3.790195,4.068079,5.452147,3.417377,4.725153,3.653333,3.421191,3.940175,4.053146
3.0,5.059154,6.078450,5.344203,4.396397,5.028470,5.307916,3.106164,5.345092,6.599246,4.450092,4.637855,4.213491,4.155858,5.354334,5.279926,4.216089,4.931579,4.654873,5.985411,3.973517,4.192009,4.775924,4.998175,4.340161,4.634930,6.098943,3.951623,5.229113,4.108239,4.241295,4.506950,4.592516
4.0,6.678788,6.934460,6.225457,5.867406,6.061585,4.838154,7.107618,4.974739,6.776303,6.507148,6.022606,4.729378,6.646331,7.582213,5.332694,6.462101,6.436086,5.783166,6.096060,4.683666,5.028592,6.572673,6.053118,6.327915,5.534602,6.696767,6.941288,5.136199,5.800475,4.977023,7.210910,5.733100
5.0,6.174869,7.057022,6.324006,5.750992,5.999975,6.048639,4.931223,6.182208,6.769226,5.616192,5.773848,5.774636,4.984680,6.251675,6.843040,5.271715,5.479590,5.643112,6.655579,5.334846,5.323617,6.340132,6.061922,5.074915,5.626931,7.162591,5.376173,5.623644,4.876794,5.756434,5.741580,5.794038
6.0,6.436985,7.373153,6.660394,5.943903,6.507677,6.608438,4.642779,6.776090,7.722663,5.933867,6.488582,5.759462,5.689716,6.799115,6.766587,5.779850,6.449465,6.148355,7.478647,5.532212,5.743965,6.675359,6.287480,6.258224,5.936508,7.497467,5.263018,6.524310,5.533979,5.592936,6.046857,6.308184
7.0,7.388463,7.711262,7.019612,6.395719,7.060411,7.040140,5.616122,6.856665,8.004917,6.771676,7.085518,7.171127,6.239822,7.321735,7.315336,6.273969,6.646385,7.228181,7.758518,6.070844,6.939355,7.249120,6.602271,7.221902,6.904050,7.914539,5.986220,6.660789,6.654843,6.865135,6.717753,7.517230
8.0,7.936030,8.749576,8.326435,7.488202,8.118023,8.029473,6.894682,8.294564,9.077548,7.546704,8.277499,7.781925,7.219263,8.237618,8.334110,7.501144,7.993432,7.937827,8.856768,7.481041,7.647036,8.261723,7.808950,8.187067,7.444968,9.013042,7.209044,7.852521,7.414459,7.478624,7.680487,7.984406
9.0,7.720156,8.762991,8.352554,8.337816,8.503413,8.554659,8.845229,8.607965,9.392793,8.229023,8.143658,8.502875,7.535722,9.061120,9.340493,8.873453,8.922227,8.540910,9.180177,8.470896,7.747336,8.331610,7.890640,8.145905,8.411376,9.208083,7.237781,10.000000,8.180000,8.272106,7.960532,8.920368
10.0,8.389883,9.074491,9.008906,7.945930,8.866910,8.575731,8.230753,8.929525,9.513204,7.978759,8.841315,8.775930,8.486717,8.730698,8.873038,8.430146,8.513939,8.583992,9.008013,7.888771,8.415070,8.862163,8.072979,8.527599,8.191430,9.574926,8.149188,8.176896,8.417309,8.146686,8.194728,8.673812
11.0,8.354920,9.055515,9.116214,7.976409,8.700544,8.843616,8.483296,9.006764,9.381368,8.188477,9.199716,8.666667,8.162356,9.061398,8.736084,8.764302,8.096705,8.833021,9.241236,9.311125,8.301205,8.404246,8.666667,8.495192,8.428321,9.553828,8.572433,8.202077,8.866667,8.570797,7.042948,9.060461
99.0,5.800739,6.890129,6.292981,5.377190,4.779950,6.202171,5.502043,6.804933,7.677955,5.066926,5.679650,5.551898,3.814768,6.080226,6.574120,4.829909,6.407835,5.748704,8.190524,5.953222,4.991552,6.607804,6.139670,5.135437,5.595553,7.212947,5.527831,6.128712,4.527529,4.763477,5.252229,4.649529

In [21]:
edu_ent.to_csv("./ConjuntosDatos/edu_estado_IDTMex.csv")

## Grupos

In [22]:
resumen = defaultdict(list)
columnas = ["Acceso", "Uso", "Aptitudes", "IDT_Mex"]

In [23]:
print("ACCESO")
for grupo in sorted(endutih_completa.Grupo.unique()):
    acceso = IDTMex.componente_acceso(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(acceso)
resumen

ACCESO

defaultdict(list,
            {'Grupo 11': [0.33125641836554853],
             'Grupo 20': [0.5651381414994829],
             'Grupo 21': [0.9139431141587864],
             'Grupo 22': [0.6417494160195532],
             'Grupo 23': [0.5100818661591037],
             'Grupo 30': [0.8512739268197405],
             'Grupo 31': [0.6609743955355059],
             'Grupo 32': [0.9346600125956602],
             'Grupo 33': [0.7316711807053552],
             'Grupo 34': [0.6536870524437441],
             'Grupo 40': [0.9042469787364235],
             'Grupo 41': [0.6971432529196147],
             'Grupo 42': [0.8495997120324384],
             'Grupo 43': [0.9798232812251504],
             'Grupo 44': [0.6977416298168035]})

In [24]:
print("USO")
for grupo in sorted(endutih_completa.Grupo.unique()):
    uso = IDTMex.componente_uso(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(uso)
resumen

USO

defaultdict(list,
            {'Grupo 11': [0.33125641836554853, 0.22676831523477603],
             'Grupo 20': [0.5651381414994829, 0.4761300504278816],
             'Grupo 21': [0.9139431141587864, 0.677930402071819],
             'Grupo 22': [0.6417494160195532, 0.644262212366932],
             'Grupo 23': [0.5100818661591037, 0.4027355079440294],
             'Grupo 30': [0.8512739268197405, 0.6798166712805527],
             'Grupo 31': [0.6609743955355059, 0.5262733963421695],
             'Grupo 32': [0.9346600125956602, 0.766807066929713],
             'Grupo 33': [0.7316711807053552, 0.6311658545597946],
             'Grupo 34': [0.6536870524437441, 0.6997153639357948],
             'Grupo 40': [0.9042469787364235, 0.7702307379191767],
             'Grupo 41': [0.6971432529196147, 0.7156435801128632],
             'Grupo 42': [0.8495997120324384, 0.7212155843000286],
             'Grupo 43': [0.9798232812251504, 0.8185670132967616],
             'Grupo 44': [0.6977416298168035, 0.7522291843637533]})

In [25]:
print("APTITUD")
for grupo in sorted(endutih_completa.Grupo.unique()):
    aptitud = IDTMex.componente_aptitudes(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(aptitud)
resumen

APTITUD

defaultdict(list,
            {'Grupo 11': [0.33125641836554853,
              0.22676831523477603,
              0.37583403339248656],
             'Grupo 20': [0.5651381414994829,
              0.4761300504278816,
              0.4995858867207141],
             'Grupo 21': [0.9139431141587864,
              0.677930402071819,
              0.5940411392192336],
             'Grupo 22': [0.6417494160195532,
              0.644262212366932,
              0.5417137440694105],
             'Grupo 23': [0.5100818661591037,
              0.4027355079440294,
              0.5339792897225246],
             'Grupo 30': [0.8512739268197405,
              0.6798166712805527,
              0.6885503771775601],
             'Grupo 31': [0.6609743955355059,
              0.5262733963421695,
              0.6487023558583568],
             'Grupo 32': [0.9346600125956602,
              0.766807066929713,
              0.7036489497634686],
             'Grupo 33': [0.7316711807053552,
              0.6311658545597946,
              0.6315645969361396],
             'Grupo 34': [0.6536870524437441,
              0.6997153639357948,
              0.6086750142394447],
             'Grupo 40': [0.9042469787364235,
              0.7702307379191767,
              0.7905889371483902],
             'Grupo 41': [0.6971432529196147,
              0.7156435801128632,
              0.7934896168610303],
             'Grupo 42': [0.8495997120324384,
              0.7212155843000286,
              0.7842874114946503],
             'Grupo 43': [0.9798232812251504,
              0.8185670132967616,
              0.8664342916237976],
             'Grupo 44': [0.6977416298168035,
              0.7522291843637533,
              0.759375726044949]})

In [26]:
print("IDTMex")
for grupo in sorted(endutih_completa.Grupo.unique()):
    idtmex = IDTMex.IDTMex(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(idtmex)
resumen

IDTMex

defaultdict(list,
            {'Grupo 11': [0.33125641836554853,
              0.22676831523477603,
              0.37583403339248656,
              2.983767001186272],
             'Grupo 20': [0.5651381414994829,
              0.4761300504278816,
              0.4995858867207141,
              5.164244541150886],
             'Grupo 21': [0.9139431141587864,
              0.677930402071819,
              0.5940411392192336,
              7.5555763433608885],
             'Grupo 22': [0.6417494160195532,
              0.644262212366932,
              0.5417137440694105,
              6.227474001684763],
             'Grupo 23': [0.5100818661591037,
              0.4027355079440294,
              0.5339792897225246,
              4.719228075857582],
             'Grupo 30': [0.8512739268197405,
              0.6798166712805527,
              0.6885503771775601,
              7.5014631467562936],
             'Grupo 31': [0.6609743955355059,
              0.5262733963421695,
              0.6487023558583568,
              6.046395879227415],
             'Grupo 32': [0.9346600125956602,
              0.766807066929713,
              0.7036489497634686,
              8.21316621762843],
             'Grupo 33': [0.7316711807053552,
              0.6311658545597946,
              0.6315645969361396,
              6.714477334932878],
             'Grupo 34': [0.6536870524437441,
              0.6997153639357948,
              0.6086750142394447,
              6.630959693997046],
             'Grupo 40': [0.9042469787364235,
              0.7702307379191767,
              0.7905889371483902,
              8.279088740919182],
             'Grupo 41': [0.6971432529196147,
              0.7156435801128632,
              0.7934896168610303,
              7.238126565851973],
             'Grupo 42': [0.8495997120324384,
              0.7212155843000286,
              0.7842874114946503,
              7.85183600831917],
             'Grupo 43': [0.9798232812251504,
              0.8185670132967616,
              0.8664342916237976,
              8.926429761335244],
             'Grupo 44': [0.6977416298168035,
              0.7522291843637533,
              0.759375726044949,
              7.318634708812127]})

In [27]:
resumen_df = pd.DataFrame.from_dict(resumen, orient='index',
                       columns=columnas)
resumen_df.insert(0, column= "ESTRATO", value= [1]*1+[2]*4+[3]*5+[4]*5)
resumen_df

          ESTRATO    Acceso       Uso  Aptitudes   IDT_Mex
Grupo 11        1  0.331256  0.226768   0.375834  2.983767
Grupo 20        2  0.565138  0.476130   0.499586  5.164245
Grupo 21        2  0.913943  0.677930   0.594041  7.555576
Grupo 22        2  0.641749  0.644262   0.541714  6.227474
Grupo 23        2  0.510082  0.402736   0.533979  4.719228
Grupo 30        3  0.851274  0.679817   0.688550  7.501463
Grupo 31        3  0.660974  0.526273   0.648702  6.046396
Grupo 32        3  0.934660  0.766807   0.703649  8.213166
Grupo 33        3  0.731671  0.631166   0.631565  6.714477
Grupo 34        3  0.653687  0.699715   0.608675  6.630960
Grupo 40        4  0.904247  0.770231   0.790589  8.279089
Grupo 41        4  0.697143  0.715644   0.793490  7.238127
Grupo 42        4  0.849600  0.721216   0.784287  7.851836
Grupo 43        4  0.979823  0.818567   0.866434  8.926430
Grupo 44        4  0.697742  0.752229   0.759376  7.318635

In [28]:
resumen_df.groupby("ESTRATO").agg("mean")

           Acceso       Uso  Aptitudes   IDT_Mex
ESTRATO
1        0.331256  0.226768   0.375834  2.983767
2        0.657728  0.550265   0.542330  5.916631
3        0.766453  0.660756   0.656228  7.021292
4        0.825711  0.755577   0.798835  7.922823

In [29]:
resumen_df.sort_values(by="IDT_Mex", ascending=False)

          ESTRATO    Acceso       Uso  Aptitudes   IDT_Mex
Grupo 43        4  0.979823  0.818567   0.866434  8.926430
Grupo 40        4  0.904247  0.770231   0.790589  8.279089
Grupo 32        3  0.934660  0.766807   0.703649  8.213166
Grupo 42        4  0.849600  0.721216   0.784287  7.851836
Grupo 21        2  0.913943  0.677930   0.594041  7.555576
Grupo 30        3  0.851274  0.679817   0.688550  7.501463
Grupo 44        4  0.697742  0.752229   0.759376  7.318635
Grupo 41        4  0.697143  0.715644   0.793490  7.238127
Grupo 33        3  0.731671  0.631166   0.631565  6.714477
Grupo 34        3  0.653687  0.699715   0.608675  6.630960
Grupo 22        2  0.641749  0.644262   0.541714  6.227474
Grupo 31        3  0.660974  0.526273   0.648702  6.046396
Grupo 20        2  0.565138  0.476130   0.499586  5.164245
Grupo 23        2  0.510082  0.402736   0.533979  4.719228
Grupo 11        1  0.331256  0.226768   0.375834  2.983767

In [30]:
print("IDTMex")
for grupo in sorted(endutih_completa.ESTRATO.unique()):
    idtmex = IDTMex.IDTMex(endutih_completa[endutih_completa.ESTRATO==grupo])

    print(f"{grupo}: {idtmex:.4f}")

IDTMex
1: 2.9838
2: 5.1838
3: 6.7429
4: 7.8827