In [19]:
import sys
sys.path.insert(0, './scripts/')

In [20]:
from collections import defaultdict
import gc
import IDTMex
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as st

In [21]:
gc.collect()

0

In [22]:
pd.set_option('display.max_columns', None)

In [23]:
base_path = "./ConjuntosDatos/"
endutih_path = base_path + "ENDUTIH2020/conjuntos_de_datos/"

In [24]:
endutih_vivhogar = pd.read_csv(endutih_path+"viv_hog_agrupados.csv")
endutih_res = pd.read_csv(endutih_path+"tr_endutih_residente_anual_2020.csv")

In [25]:
endutih_completa = pd.merge(endutih_vivhogar,endutih_res.drop(["UPM_DIS","ESTRATO","ENT","DOMINIO", "EST_DIS", "TLOC"], axis=1), on = ["UPM","VIV_SEL", "HOGAR"])
endutih_completa

,P1_1,P1_2,P1_3,P1_4,P1_5_1,P1_5_2,P1_5_3,P2_1,P2_2,P2_3,FAC_VIV,P4_1_1,P4_1_2,P4_1_3,P4_1_4,P4_1_5,P4_1_6,P4_1_6_1,P4_1_6_2,P4_2_1,P4_2_2,P4_2_3,P4_3,P4_4,P4_5,P4_6_1,P4_6_2,P4_6_3,P4_6_4,P4_6_5,P4_6_6,P4_7_1,P4_7_2,P4_7_3,P4_7_4,P4_8,P5_1,P5_2_1,P5_2_2,P5_3_1,P5_3_2,P5_4,P5_5,P5_6_1,P5_6_2,P5_6_3,P5_6_4,P5_6_5,P5_7_1,P5_7_2,P5_8_2,P5_9_2,P5_10_2,P5_7_3,P5_8_3,P5_7_4,P5_8_4,P5_9_4,P5_7_5,P5_8_5,P5_7_6,P5_8_6,P5_7_7,P5_8_7,P5_7_8,P5_8_8,P5_11_1,P5_11_2,P5_11_3,FAC_HOG,DOMINIO,TLOC,ESTRATO,Grupo,UPM,UPM_DIS,EST_DIS,ENT,HOGAR,VIV_SEL,NUM_REN,PAREN,SEXO,EDAD,DIA,MES,P3_7,NIVEL,GRADO,P3_9_1,P3_9_2,P3_9_3,P3_10,P3_11,P3_12,FAC_HOGAR
0,2,1,1,1,1,2,2,2,1,1.0,572,2,1,1,2,2,1,2.0,2.0,2,2,2,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,1.0,2,2,2,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,3.0,3.0,3.0,575,U,1,1,11,206264,570,17,2,1,1,1,1,2,54,27.0,3.0,2.0,0.0,0.0,9.0,9.0,1.0,6.0,4.0,NaN,575
1,2,1,1,1,1,2,2,2,1,1.0,572,2,1,1,2,2,1,2.0,2.0,2,2,2,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,1.0,2,2,2,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,3.0,3.0,3.0,575,U,1,1,11,206264,570,17,2,1,1,2,3,2,22,7.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,1.0,NaN,1.0,575
2,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,1,1,2,36,29.0,6.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,575
3,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,2,3,1,20,29.0,3.0,2.0,6.0,2.0,1.0,1.0,1.0,1.0,NaN,1.0,575
4,2,1,1,1,1,1,1,6,1,1.0,572,2,1,2,1,1,1,5.0,5.0,2,1,1,0.0,1,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,3.0,575,U,1,1,11,206264,570,17,2,1,2,3,3,2,19,20.0,2.0,2.0,6.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205276,3,1,1,1,1,1,1,5,1,1.0,271,1,2,2,1,1,1,5.0,5.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,2,1,1,2,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,400.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,1.0,3.0,271,U,1,4,42,3201181,8162,340,32,1,3,5,3,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,271
205277,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,1,1,1,43,16.0,9.0,2.0,7.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,271
205278,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,2,2,2,46,25.0,4.0,2.0,7.0,3.0,1.0,1.0,1.0,1.0,NaN,1.0,271
205279,3,1,1,1,1,1,1,3,1,1.0,271,1,2,2,1,1,1,3.0,3.0,2,1,1,0.0,1,3.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1,1.0,2.0,2.0,2.0,0.0,1,1,1,1,1,2,2.0,1.0,609.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,1.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,4,3,3,1,15,8.0,12.0,1.0,3.0,3.0,1.0,1.0,1.0,5.0,4.0,NaN,271
205280,3,1,1,1,1,1,1,1,1,1.0,271,1,1,2,1,2,1,1.0,1.0,2,1,1,0.0,1,3.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,0.0,2,0.0,0.0,0.0,0.0,5.0,1,1,2,1,1,2,2.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,250.0,2.0,0.0,2.0,0.0,2.0,0.0,1.0,3.0,1.0,271,U,1,4,42,3201181,8162,340,32,1,5,1,1,2,41,24.0,1.0,2.0,10.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,271

In [26]:
resumen = defaultdict(list)
columnas = ["Acceso", "Uso", "Aptitudes", "IDT_Mex"]

In [27]:
print("ACCESO")
for grupo in sorted(endutih_completa.Grupo.unique()):
    acceso = IDTMex.componente_acceso(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(acceso)
resumen

ACCESO

defaultdict(list,
            {'Grupo 11': [0.33125641836554853],
             'Grupo 20': [0.5651381414994829],
             'Grupo 21': [0.9139431141587864],
             'Grupo 22': [0.6417494160195532],
             'Grupo 23': [0.5100818661591037],
             'Grupo 30': [0.8512739268197405],
             'Grupo 31': [0.6609743955355059],
             'Grupo 32': [0.9346600125956602],
             'Grupo 33': [0.7316711807053552],
             'Grupo 34': [0.6536870524437441],
             'Grupo 40': [0.9042469787364235],
             'Grupo 41': [0.6971432529196147],
             'Grupo 42': [0.8495997120324384],
             'Grupo 43': [0.9798232812251504],
             'Grupo 44': [0.6977416298168035]})

In [28]:
print("USO")
for grupo in sorted(endutih_completa.Grupo.unique()):
    uso = IDTMex.componente_uso(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(uso)
resumen

USO

defaultdict(list,
            {'Grupo 11': [0.33125641836554853, 0.22676831523477603],
             'Grupo 20': [0.5651381414994829, 0.4761300504278816],
             'Grupo 21': [0.9139431141587864, 0.677930402071819],
             'Grupo 22': [0.6417494160195532, 0.644262212366932],
             'Grupo 23': [0.5100818661591037, 0.4027355079440294],
             'Grupo 30': [0.8512739268197405, 0.6798166712805527],
             'Grupo 31': [0.6609743955355059, 0.5262733963421695],
             'Grupo 32': [0.9346600125956602, 0.766807066929713],
             'Grupo 33': [0.7316711807053552, 0.6311658545597946],
             'Grupo 34': [0.6536870524437441, 0.6997153639357948],
             'Grupo 40': [0.9042469787364235, 0.7702307379191767],
             'Grupo 41': [0.6971432529196147, 0.7156435801128632],
             'Grupo 42': [0.8495997120324384, 0.7212155843000286],
             'Grupo 43': [0.9798232812251504, 0.8185670132967616],
             'Grupo 44': [0.6977416298168035, 0.7522291843637533]})

In [29]:
print("APTITUD")
for grupo in sorted(endutih_completa.Grupo.unique()):
    aptitud = IDTMex.componente_aptitudes(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(aptitud)
resumen

APTITUD

defaultdict(list,
            {'Grupo 11': [0.33125641836554853,
              0.22676831523477603,
              0.37583403339248656],
             'Grupo 20': [0.5651381414994829,
              0.4761300504278816,
              0.4995858867207141],
             'Grupo 21': [0.9139431141587864,
              0.677930402071819,
              0.5940411392192336],
             'Grupo 22': [0.6417494160195532,
              0.644262212366932,
              0.5417137440694105],
             'Grupo 23': [0.5100818661591037,
              0.4027355079440294,
              0.5339792897225246],
             'Grupo 30': [0.8512739268197405,
              0.6798166712805527,
              0.6885503771775601],
             'Grupo 31': [0.6609743955355059,
              0.5262733963421695,
              0.6487023558583568],
             'Grupo 32': [0.9346600125956602,
              0.766807066929713,
              0.7036489497634686],
             'Grupo 33': [0.7316711807053552,
              0.6311658545597946,
              0.6315645969361396],
             'Grupo 34': [0.6536870524437441,
              0.6997153639357948,
              0.6086750142394447],
             'Grupo 40': [0.9042469787364235,
              0.7702307379191767,
              0.7905889371483902],
             'Grupo 41': [0.6971432529196147,
              0.7156435801128632,
              0.7934896168610303],
             'Grupo 42': [0.8495997120324384,
              0.7212155843000286,
              0.7842874114946503],
             'Grupo 43': [0.9798232812251504,
              0.8185670132967616,
              0.8664342916237976],
             'Grupo 44': [0.6977416298168035,
              0.7522291843637533,
              0.759375726044949]})

In [30]:
print("IDTMex")
for grupo in sorted(endutih_completa.Grupo.unique()):
    idtmex = IDTMex.IDTMex(endutih_completa[endutih_completa.Grupo==grupo])
    resumen[f"Grupo {grupo}"].append(idtmex)
resumen

IDTMex

defaultdict(list,
            {'Grupo 11': [0.33125641836554853,
              0.22676831523477603,
              0.37583403339248656,
              2.983767001186272],
             'Grupo 20': [0.5651381414994829,
              0.4761300504278816,
              0.4995858867207141,
              5.164244541150886],
             'Grupo 21': [0.9139431141587864,
              0.677930402071819,
              0.5940411392192336,
              7.5555763433608885],
             'Grupo 22': [0.6417494160195532,
              0.644262212366932,
              0.5417137440694105,
              6.227474001684763],
             'Grupo 23': [0.5100818661591037,
              0.4027355079440294,
              0.5339792897225246,
              4.719228075857582],
             'Grupo 30': [0.8512739268197405,
              0.6798166712805527,
              0.6885503771775601,
              7.5014631467562936],
             'Grupo 31': [0.6609743955355059,
              0.5262733963421695,
              0.6487023558583568,
              6.046395879227415],
             'Grupo 32': [0.9346600125956602,
              0.766807066929713,
              0.7036489497634686,
              8.21316621762843],
             'Grupo 33': [0.7316711807053552,
              0.6311658545597946,
              0.6315645969361396,
              6.714477334932878],
             'Grupo 34': [0.6536870524437441,
              0.6997153639357948,
              0.6086750142394447,
              6.630959693997046],
             'Grupo 40': [0.9042469787364235,
              0.7702307379191767,
              0.7905889371483902,
              8.279088740919182],
             'Grupo 41': [0.6971432529196147,
              0.7156435801128632,
              0.7934896168610303,
              7.238126565851973],
             'Grupo 42': [0.8495997120324384,
              0.7212155843000286,
              0.7842874114946503,
              7.85183600831917],
             'Grupo 43': [0.9798232812251504,
              0.8185670132967616,
              0.8664342916237976,
              8.926429761335244],
             'Grupo 44': [0.6977416298168035,
              0.7522291843637533,
              0.759375726044949,
              7.318634708812127]})

In [37]:
resumen_df = pd.DataFrame.from_dict(resumen, orient='index',
                       columns=columnas)
resumen_df.insert(0, column= "ESTRATO", value= [1]*1+[2]*4+[3]*5+[4]*5)
resumen_df

          ESTRATO    Acceso       Uso  Aptitudes   IDT_Mex
Grupo 11        1  0.331256  0.226768   0.375834  2.983767
Grupo 20        2  0.565138  0.476130   0.499586  5.164245
Grupo 21        2  0.913943  0.677930   0.594041  7.555576
Grupo 22        2  0.641749  0.644262   0.541714  6.227474
Grupo 23        2  0.510082  0.402736   0.533979  4.719228
Grupo 30        3  0.851274  0.679817   0.688550  7.501463
Grupo 31        3  0.660974  0.526273   0.648702  6.046396
Grupo 32        3  0.934660  0.766807   0.703649  8.213166
Grupo 33        3  0.731671  0.631166   0.631565  6.714477
Grupo 34        3  0.653687  0.699715   0.608675  6.630960
Grupo 40        4  0.904247  0.770231   0.790589  8.279089
Grupo 41        4  0.697143  0.715644   0.793490  7.238127
Grupo 42        4  0.849600  0.721216   0.784287  7.851836
Grupo 43        4  0.979823  0.818567   0.866434  8.926430
Grupo 44        4  0.697742  0.752229   0.759376  7.318635

In [38]:
resumen_df.groupby("ESTRATO").agg("mean")

           Acceso       Uso  Aptitudes   IDT_Mex
ESTRATO
1        0.331256  0.226768   0.375834  2.983767
2        0.657728  0.550265   0.542330  5.916631
3        0.766453  0.660756   0.656228  7.021292
4        0.825711  0.755577   0.798835  7.922823

In [41]:
resumen_df.sort_values(by="IDT_Mex", ascending=False)

          ESTRATO    Acceso       Uso  Aptitudes   IDT_Mex
Grupo 43        4  0.979823  0.818567   0.866434  8.926430
Grupo 40        4  0.904247  0.770231   0.790589  8.279089
Grupo 32        3  0.934660  0.766807   0.703649  8.213166
Grupo 42        4  0.849600  0.721216   0.784287  7.851836
Grupo 21        2  0.913943  0.677930   0.594041  7.555576
Grupo 30        3  0.851274  0.679817   0.688550  7.501463
Grupo 44        4  0.697742  0.752229   0.759376  7.318635
Grupo 41        4  0.697143  0.715644   0.793490  7.238127
Grupo 33        3  0.731671  0.631166   0.631565  6.714477
Grupo 34        3  0.653687  0.699715   0.608675  6.630960
Grupo 22        2  0.641749  0.644262   0.541714  6.227474
Grupo 31        3  0.660974  0.526273   0.648702  6.046396
Grupo 20        2  0.565138  0.476130   0.499586  5.164245
Grupo 23        2  0.510082  0.402736   0.533979  4.719228
Grupo 11        1  0.331256  0.226768   0.375834  2.983767

In [40]:
print("IDTMex")
for grupo in sorted(endutih_completa.ESTRATO.unique()):
    idtmex = IDTMex.IDTMex(endutih_completa[endutih_completa.ESTRATO==grupo])

    print(f"{grupo}: {idtmex:.4f}")

IDTMex
1: 2.9838
2: 5.1838
3: 6.7429
4: 7.8827